### ISSUE TITLE
[criticism]

### ISSUE THREAD

**Issue by s0md3v** [Ekultek/XanXSS#3]
Hi there,

There are a few problems with your approach

**Lack of knowledge**
I don't intend to sound disrespectful but I believe you don't know much about XSS.
Let's take this payload generated by your tool for example,
```
<xanxssjAvASCRIpT:/*--></ScRiPt></XANxsS</tiTle></STyle><SvG/OnLOAD\u006c='aLErt(1);'/>
```
It can be divided into two parts

#### Passive
`<xanxssjAvASCRIpT:/*--></ScRiPt></XANxsS</tiTle></STyle>`

It is intended to break out of various contexts and obfuscate the payload but `javascript:/*` is useless here and won't contribute anything if it is intended to be used in URI context. The other closing tags simply increasing the chances of being detected by a WAF.\
Closing tags should be used only and only when they are required to break out of a context.

#### Active
`<SvG/OnLOAD\u006c='aLErt(1);'/>`

I don't know where to start with this.
No, you can't put `\u006c` between event handler and `=`, browsers and HTML specification don't allow that.\
A function name is case sensitive, which means `alert` and `aLErt` are not the same and hence the function will not execute.

**Determining if a payload works**
I believe you are using literal `if payload in source_code` method to see if a payload got properly reflected in the source code or not but it doesn't work.\ Characters can be altered by the web application and the payload might work given that.\
For example, if your payload is getting reflected into JavaScript context and the double quotes (`"`) are  being escaped using backslash (`\`), the payload `<junk><svg""></script><svg onload=alert()>` will still work.

You might be using fuzzy matching or a similar technique but that won't be able to determine if a payload works either.

**Re-inventing the wheel, a bad wheel**
Your read-me has a statement,
> Unlike other XSS scanners that just run through a list of payloads.

No, you didn't do anything new. There's XSSniper, XSStrike and intellifuzz-XSS and a few other tools that generate their own payloads and they actually work.

You tried to do the same thing but unfortunately your work lacks research.

**Final words**
In a professional tone, I think your tool doesn't work the way one might expect it to. It lacks research and fails in the most basic principles of XSS detection.

As a homie, I think it sucks and you should contribute to other projects instead of trying to do something that has already been done.

I spent time writing this and now it's up to you whether you want to do something about it (I recommend deleting) or say I have a small penis like you said to @stamparm.

Regards

**Comment by Ekultek** [comment]
Hi, I actually use your tool over mine so on that note nah stam kinda has it coming for awhile (which is a whole different story). I wrote this tool as a basic concept for learning and starting I’ve been slowly updating it and not releasing th updates (mostly because I’ve been busy with personal shit). It actually does not work the way it’s suppose to, there’s multiple false positives it, the polyglot isn’t random, the random generations isn’t cryptographically secure, etc.

But now I have a question for you, why did you even bother to write this? Clearly you have either one of two things, a problem with me, or just wanted to come and try to cause trouble on github. Or I could be mistaken and you initentionally came and wasted your time writing a review on a tool with less than 40 stars.

**Comment by s0md3v** [comment]
I don't have a problem with you.
I came, I saw and I was concerned why it's being promoted by kitploit.
I guess you think I have problem with you because of my tweet. Mate, I don't even know you.
But what you did with stamparm isn't acceptable, that's all.
No one actually cares about "The WAF signatures and tamper scripts were taken from sqlmap".
Giving credits is cool, try it

**Comment by Ekultek** [comment]
Homie did you even bother to look at wafw00f sqlmap burp etc. Go do that and come back. You wanna start shit thats on you I dont mind but dont call me out and expect nothing to happen. I originally gave credit to sqlmap in comments until he tried to pull that bullshit among other things. You have no idea the whole story just what you've seen. Now I apologize if this reply sounds harsh because your tool actually was what inspired me to start writing this one, as I mentioned this is not complete and still a work in progress. Thank you for your criticism though it means alot tbh. I'll look into it when I have more time.On Apr 7, 2019 10:51 AM, Somdev Sangwan <notifications@github.com> wrote:I don't have a problem with you.
I came, I saw and I was concerned why it's being promoted by kitploit.
I guess you think I have problem with you because of my tweet. Mate, I don't even know you.
But what you did with stamparm isn't acceptable, that's all.
No one actually cares about "The WAF signatures and tamper scripts were taken from sqlmap".
Giving credits is cool, try it

**Comment by s0md3v** [comment]
I don't wanna start shit. Thank you, bye.

**Comment by Ekultek** [comment]
You sure? because between twitter and this it sure seems like you do. don’t throw shade unless you’re willing to go ahead and look into every scenario, what you’re doing is petty and close minded. This could of easily been solved through a simple dm on Twitter or whatever, but nope you decided to go public. So when something of yours ends up public don’t be surprised. I’ve got nothing to lose and if you’re smart that scares you.

**Comment by Ekultek** [comment]
Have a good day.
